# Testing this script
# It should grab a list of display names from a .csv
# then find the relevant samAccountName from AD and output it to a different .csv
# This script was generated by OpenAI - ChatGPT

Import-Module ActiveDirectory

# Read CSV file
$csv = Import-Csv -Path "C:\scripts\ADNameScraper\testnames.csv"

$results = @()

foreach ($row in $csv) {
    $displayName = $row.DisplayName
    $user = Get-ADUser -Filter {DisplayName -eq $displayName} -Properties sAMAccountName

    # Check if user with this display name exists
    if ($user) {
        $samAccountName = $user.sAMAccountName
        $results += [pscustomobject]@{
            DisplayName = $displayName
            sAMAccountName = $samAccountName
        }
    } else {
        Write-Host "User with display name $displayName not found"
    }
}

# Export results to CSV file
$results | Export-Csv -Path "C:\scripts\ADNameScraper\samaccountnames.csv" -NoTypeInformation